create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  role text not null default 'client' check (role in ('client', 'writer', 'admin')),
  avatar text default '*',
  location text default 'India',
  coins integer not null default 0,
  level integer not null default 1,
  orders integer not null default 0,
  rating numeric(3, 1) not null default 5.0,
  streak integer not null default 0,
  rank integer not null default 0,
  completed integer not null default 0,
  delivered integer not null default 0,
  "onTime" integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title text not null,
  subject text not null,
  sem integer not null check (sem between 1 and 8),
  dept text not null,
  teacher text,
  type text not null,
  "uploadedBy" text not null,
  date date not null default current_date,
  size text,
  downloads integer not null default 0,
  rating numeric(3, 1) not null default 5.0,
  desc text,
  tags text[] not null default array[]::text[],
  reviews jsonb not null default '[]'::jsonb,
  comments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pending_resources (
  id bigint primary key,
  title text not null,
  subject text not null,
  sem integer not null check (sem between 1 and 8),
  dept text not null,
  teacher text,
  type text not null,
  desc text,
  "userId" text not null,
  "uploadedBy" text not null,
  date date not null default current_date,
  size text,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  tags text[] not null default array[]::text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deadlines (
  id text primary key,
  "userId" text not null,
  name text not null,
  subject text not null,
  "orderId" text not null default '',
  "dueDate" timestamptz not null,
  status text not null default 'Active' check (status in ('Active', 'Completed', 'Overdue', 'Pending')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  "userId" text not null,
  subject text not null,
  pages integer not null default 1,
  type text,
  deadline text,
  price numeric(10, 2),
  status text not null default 'Pending' check (status in ('Pending', 'In Progress', 'Under Review', 'Delivered', 'Cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contributors (
  name text primary key,
  rank integer not null default 0,
  uploads integer not null default 0,
  downloads integer not null default 0,
  points integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists deadlines_user_id_idx on public.deadlines ("userId");
create index if not exists deadlines_due_date_idx on public.deadlines ("dueDate");
create index if not exists orders_user_id_idx on public.orders ("userId");
create index if not exists pending_resources_user_id_idx on public.pending_resources ("userId");

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists resources_set_updated_at on public.resources;
create trigger resources_set_updated_at
before update on public.resources
for each row
execute function public.set_updated_at();

drop trigger if exists pending_resources_set_updated_at on public.pending_resources;
create trigger pending_resources_set_updated_at
before update on public.pending_resources
for each row
execute function public.set_updated_at();

drop trigger if exists deadlines_set_updated_at on public.deadlines;
create trigger deadlines_set_updated_at
before update on public.deadlines
for each row
execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

drop trigger if exists contributors_set_updated_at on public.contributors;
create trigger contributors_set_updated_at
before update on public.contributors
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.resources enable row level security;
alter table public.pending_resources enable row level security;
alter table public.deadlines enable row level security;
alter table public.orders enable row level security;
alter table public.contributors enable row level security;

drop policy if exists "profiles_select_self" on public.profiles;
create policy "profiles_select_self"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "resources_public_read" on public.resources;
create policy "resources_public_read"
on public.resources
for select
to anon, authenticated
using (true);

drop policy if exists "resources_authenticated_write" on public.resources;
create policy "resources_authenticated_write"
on public.resources
for all
to authenticated
using (true)
with check (true);

drop policy if exists "pending_resources_authenticated_read" on public.pending_resources;
create policy "pending_resources_authenticated_read"
on public.pending_resources
for select
to authenticated
using (true);

drop policy if exists "pending_resources_authenticated_write" on public.pending_resources;
create policy "pending_resources_authenticated_write"
on public.pending_resources
for all
to authenticated
using (true)
with check (true);

drop policy if exists "deadlines_select_owner" on public.deadlines;
create policy "deadlines_select_owner"
on public.deadlines
for select
to authenticated
using ("userId" = auth.uid()::text);

drop policy if exists "deadlines_write_owner" on public.deadlines;
create policy "deadlines_write_owner"
on public.deadlines
for all
to authenticated
using ("userId" = auth.uid()::text)
with check ("userId" = auth.uid()::text);

drop policy if exists "orders_select_owner" on public.orders;
create policy "orders_select_owner"
on public.orders
for select
to authenticated
using ("userId" = auth.uid()::text);

drop policy if exists "orders_write_owner" on public.orders;
create policy "orders_write_owner"
on public.orders
for all
to authenticated
using ("userId" = auth.uid()::text)
with check ("userId" = auth.uid()::text);

drop policy if exists "contributors_public_read" on public.contributors;
create policy "contributors_public_read"
on public.contributors
for select
to anon, authenticated
using (true);

drop policy if exists "contributors_authenticated_write" on public.contributors;
create policy "contributors_authenticated_write"
on public.contributors
for all
to authenticated
using (true)
with check (true);
